---
- hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: webserver_user4
      location: northeurope
    register: rg
  - debug:
      var: rg