---
- hosts: localhost
  vars:
   host: "10.172.10.1"
   username: "user4"
   vlanid: "104"
   vdom: "root"
   ssl_verify: "False"
  vars_prompt:
   - name: password
     prompt: "Type the password of your fortigate admin account"
     private: no
  tasks:
  - name: Configure interface
    fortios_system_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      system_interface:
        name: "vlan_{{ vlanid }}"
        allowaccess: "ping"
        mode: "static"
        ip: "10.172.{{ vlanid }}.1/24"
        type: "vlan"
        vlanid: "{{ vlanid }}"
        role: "lan"
        interface: "switch"
        status: "up"
        vdom: "root"