---
- hosts: localhost
  vars:
    hostname: "vcenter.ansible.local"
    esxihostname: "esxi.ansible.local"
    username: "user4@vsphere.local"
    password: "Password1!"
    nfs_user: "user4"
    portgroup_name: "vlan104"
    vlan_id: "104"
  tasks:
  - name: Add NFS Storage ESXi
    vmware_host_datastore:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      esxi_hostname: "{{ esxihostname }}"
      datastore_name: "datastore_{{ nfs_user }}"
      datastore_type: "nfs"
      nfs_server: "storage.ansible.local"
      nfs_path: "/storage/{{ nfs_user }}"
      nfs_ro: "no"
      state: "present"
      validate_certs: "False"
    delegate_to: "localhost"

- name: Add a PortGroup to VMware vSwitch
    vmware_portgroup:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      switch_name: "vSwitch0"
      esxi_hostname: "{{ esxihostname }}"
      portgroup_name: "{{ portgroup_name }}"
      vlan_id: "{{ vlan_id }}"
    delegate_to: localhost